//
//  DeveloperPreview.swift
//  HomeAway
//
//  Created by fiififranklin on 28/09/2024.
//

import Foundation

class DeveloperPreview {
    var listings:[Listing] = [
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .gym, .parking],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .gym, .parking],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .airConditioning,.breakfast],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .airConditioning,.breakfast],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .airConditioning,.breakfast],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .airConditioning,.breakfast],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .airConditioning,.breakfast],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .airConditioning,.breakfast],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .airConditioning,.breakfast],
            type: [.apartment, .house]
        ),
        .init(
            id:NSUUID().uuidString,
            ownerId:NSUUID().uuidString,
            ownerName:"Fiififranklin",
            ownerAvatar:"hello",
            numberOfBathrooms: 2,
            numberOfGuests:  4,
            numberOfBedrooms:  4,
            numberOfBeds:  4,
            pricePerNight:500,
            ImageUrls: ["Listing-1","Listing-2","Listing-3"],
            latitude: 25.7850,
            longitude: -80.1910,
            address: "124 Main street",
            city: "New York",
            state: "New York",
            country: "USA",
            title: "Super cool house",
            rating: 4.5,
            features: [.selfCheckin, .superHost],
            amenities: [.pool, .airConditioning,.breakfast],
            type: [.apartment, .house]
        ),
        
    ]
}
